##
## EPITECH PROJECT, 2022
## Makefile
## File description:
##
##

all:
		cd antman && make
		cd giantman && make

fclean:
		cd antman && make fclean
		cd giantman && make fclean

.PHONY: debug clean fclean re
