version: '3'



services:
  poll:
    build: poll
    restart: on-failure
    depends_on:
      - redis
    ports:
      - "5000:80"
    networks:
      - poll-tier


  redis:
    image: "redis:alpine"
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier

  worker:
    build: worker
    restart: on-failure
    depends_on:
      - redis
      - db
    networks:
      - poll-tier
      - result-tier
      - back-tier

  db:
    image: "postgres:9.4"
    restart: on-failure
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=posgres"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - result-tier
      - back-tier

  result:
    build: result
    restart: on-failure
    depends_on:
      - db
    ports:
      - "5001:80"
    networks:
      - result-tier


networks:
  poll-tier:

  result-tier: 

  back-tier:

volumes:
  db-data: