##
## EPITECH PROJECT, 2021
## Makefile
## File description:
## ded
##


all:
		make -C generator
		make -C solver


fclean:
	make fclean -C solver
	make fclean -C generator


.PHONY: fclean all clean
